# Copyright 2026 The OpenChoreo Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: observability-tracing-openobserve
description: A Helm chart for OpenChoreo Tracing Module for OpenObserve
type: application
version: 0.2.3
appVersion: "0.2.3"
keywords:
  - openobserve
  - openchoreo
  - tracing
maintainers:
  - name: OpenChoreo Team
home: https://github.com/openchoreo/community-modules
dependencies:
  - name: opentelemetry-collector
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.146.1
    condition: opentelemetry-collector.enabled
  - name: openobserve-standalone
    version: 0.80.3
    repository: https://charts.openobserve.ai
    condition: openobserve-standalone.enabled
  - name: openobserve
    version: "0.60.3"
    repository: https://charts.openobserve.ai
    condition: openobserve.enabled
